<a href="https://colab.research.google.com/github/Pritishcoder07/Movie_Recommendation/blob/main/Movie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [127]:
import numpy as np
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [128]:
df= pd.read_csv('netflix_titles_nov_2019.csv.zip')

In [129]:
df.head()

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,type
0,81193313,Chocolate,NaN,"Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang ...",South Korea,"November 30, 2019",2019,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",Brought together by meaningful meals in the pa...,TV Show
1,81197050,Guatemala: Heart of the Mayan World,"Luis Ara, Ignacio Jaunsolo",Christian Morales,NaN,"November 30, 2019",2019,TV-G,67 min,"Documentaries, International Movies","From Sierra de las Minas to Esquipulas, explor...",Movie
2,81213894,The Zoya Factor,Abhishek Sharma,"Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...",India,"November 30, 2019",2019,TV-14,135 min,"Comedies, Dramas, International Movies",A goofy copywriter unwittingly convinces the I...,Movie
3,81082007,Atlantics,Mati Diop,"Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...","France, Senegal, Belgium","November 29, 2019",2019,TV-14,106 min,"Dramas, Independent Movies, International Movies","Arranged to marry a rich man, young Ada is cru...",Movie
4,80213643,Chip and Potato,NaN,"Abigail Oliver, Andrea Libman, Briana Buckmast...","Canada, United Kingdom",NaN,2019,TV-Y,2 Seasons,Kids' TV,"Lovable pug Chip starts kindergarten, makes ne...",TV Show

In [130]:
# show_id
# title
# director
# cast
# rating
# duration
# type
movie = df[['show_id','title','director','cast','duration','type']]

In [131]:
# Re-create movie DataFrame from original df to ensure correct data
movie = df[['show_id','title','director','cast','duration','type']].copy()

In [132]:
# Fill NaN values in 'director' and 'cast' columns with empty strings
movie['director'] = movie['director'].fillna('')
movie['cast'] = movie['cast'].fillna('')

The `convert3` function should be defined in a previous cell (cell `17f97521`). If that cell was not run or was modified, please ensure it contains the correct definition:
```python
def convert3(obj):
  L = []
  if isinstance(obj, str) and obj.strip() != '':
    names = [name.strip() for name in obj.split(',')]
    for name in names:
        if len(L) < 3: # Get up to 3 names
          L.append(name)
        else:
          break
  return L
```

In [133]:
# Apply the director processing to split names into lists
movie['director'] = movie['director'].apply(lambda x: [d.strip() for d in x.split(',')] if isinstance(x, str) and x.strip() != '' else [])

In [134]:
# Apply the convert3 function to the 'cast' column to get up to 3 names
movie['cast'] = movie['cast'].apply(convert3)

In [135]:
# Process 'duration' column to split into lists (e.g., ['1', 'Season'] or ['67', 'min'])
movie['duration'] = movie['duration'].apply(lambda x: x.split() if isinstance(x, str) else x)

In [136]:
# Process 'type' column to split into lists (e.g., ['TV', 'Show'] or ['Movie'])
movie['type'] = movie['type'].apply(lambda x: x.split() if isinstance(x, str) else x)

In [137]:
# Display the head of the DataFrame to verify the changes
movie.head()

,show_id,title,director,cast,duration,type
0,81193313,Chocolate,[],"[Ha Ji-won, Yoon Kye-sang, Jang Seung-jo]","[1, Season]","[TV, Show]"
1,81197050,Guatemala: Heart of the Mayan World,"[Luis Ara, Ignacio Jaunsolo]",[Christian Morales],"[67, min]",[Movie]
2,81213894,The Zoya Factor,[Abhishek Sharma],"[Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor]","[135, min]",[Movie]
3,81082007,Atlantics,[Mati Diop],"[Mama Sane, Amadou Mbow, Ibrahima Traore]","[106, min]",[Movie]
4,80213643,Chip and Potato,[],"[Abigail Oliver, Andrea Libman, Briana Buckmas...","[2, Seasons]","[TV, Show]"

In [138]:
movie.head()

,show_id,title,director,cast,duration,type
0,81193313,Chocolate,[],"[Ha Ji-won, Yoon Kye-sang, Jang Seung-jo]","[1, Season]","[TV, Show]"
1,81197050,Guatemala: Heart of the Mayan World,"[Luis Ara, Ignacio Jaunsolo]",[Christian Morales],"[67, min]",[Movie]
2,81213894,The Zoya Factor,[Abhishek Sharma],"[Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor]","[135, min]",[Movie]
3,81082007,Atlantics,[Mati Diop],"[Mama Sane, Amadou Mbow, Ibrahima Traore]","[106, min]",[Movie]
4,80213643,Chip and Potato,[],"[Abigail Oliver, Andrea Libman, Briana Buckmas...","[2, Seasons]","[TV, Show]"

In [139]:
def is_empty_list(lst):
    return not lst or all(not item.strip() for item in lst)

In [140]:
print(f"Shape before dropping rows: {movie.shape}")

Shape before dropping rows: (5837, 6)

In [141]:
movie = movie[~movie['director'].apply(is_empty_list) & ~movie['cast'].apply(is_empty_list)]

In [143]:
movie.head()

,show_id,title,director,cast,duration,type
1,81197050,Guatemala: Heart of the Mayan World,"[Luis Ara, Ignacio Jaunsolo]",[Christian Morales],"[67, min]",[Movie]
2,81213894,The Zoya Factor,[Abhishek Sharma],"[Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor]","[135, min]",[Movie]
3,81082007,Atlantics,[Mati Diop],"[Mama Sane, Amadou Mbow, Ibrahima Traore]","[106, min]",[Movie]
5,81172754,Crazy people,[Moses Inwang],"[Ramsey Nouah, Chigul, Sola Sobowale]","[107, min]",[Movie]
6,81120982,I Lost My Body,[Jérémy Clapin],"[Hakim Faris, Victoire Du Bois, Patrick d'Assu...","[81, min]",[Movie]

In [146]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3588 entries, 1 to 5836
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   show_id   3588 non-null   int64
 1   title     3588 non-null   object
 2   director  3588 non-null   object
 3   cast      3588 non-null   object
 4   duration  3588 non-null   object
 5   type      3588 non-null   object
dtypes: int64(1), object(5)
memory usage: 196.2+ KB

In [148]:
movie.shape

(3588, 6)